// <auto-generated />
using System;
using AlgoTrading.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AlgoTrading.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AlgoTradingDbContext))]
    partial class AlgoTradingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("AlgoTrading.Infrastructure.Persistence.BacktestRunRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AnnualisedReturn")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Calmar")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("FinalEquity")
                        .HasColumnType("TEXT");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("From")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("InitialCash")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MaxDrawdown")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("RanAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Sharpe")
                        .HasColumnType("TEXT");

                    b.Property<string>("StrategyJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StrategyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("To")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalCosts")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalReturn")
                        .HasColumnType("TEXT");

                    b.Property<int>("TradeCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Universe")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("WinRate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Fingerprint");

                    b.HasIndex("RanAt");

                    b.ToTable("BacktestRuns", (string)null);
                });

            modelBuilder.Entity("AlgoTrading.Infrastructure.Persistence.DailyBarRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AdjustedClose")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Close")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("High")
                        .HasColumnType("TEXT");

                    b.Property<int>("InstrumentId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Low")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Open")
                        .HasColumnType("TEXT");

                    b.Property<long>("Volume")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("InstrumentId", "Date")
                        .IsUnique();

                    b.ToTable("DailyBars", (string)null);
                });

            modelBuilder.Entity("AlgoTrading.Infrastructure.Persistence.InstrumentRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Symbol")
                        .IsUnique();

                    b.ToTable("Instruments", (string)null);
                });

            modelBuilder.Entity("AlgoTrading.Infrastructure.Persistence.DailyBarRow", b =>
                {
                    b.HasOne("AlgoTrading.Infrastructure.Persistence.InstrumentRow", "Instrument")
                        .WithMany("Bars")
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instrument");
                });

            modelBuilder.Entity("AlgoTrading.Infrastructure.Persistence.InstrumentRow", b =>
                {
                    b.Navigation("Bars");
                });
#pragma warning restore 612, 618
        }
    }
}
