<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>AlgoTrading.Architecture.Tests</RootNamespace>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/AlgoTrading.Domain/AlgoTrading.Domain.csproj" />
    <ProjectReference Include="../../src/AlgoTrading.Application/AlgoTrading.Application.csproj" />
    <ProjectReference Include="../../src/AlgoTrading.Infrastructure/AlgoTrading.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="Shouldly" />
    <PackageReference Include="NetArchTest.Rules" />
  </ItemGroup>

</Project>
